version: 1.0.{build}
image: Visual Studio 2015

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    
    git submodule update --init --recursive
    
    
build_script:
- ps: >-
    
    # Build robot code
    
    cd RobotCode\snobot2017
    
    cmd /c gradlew.bat build jacocoTestReport
    
    # Build SmartDashboard
    
    cd ..\..\SmartDashboardExtensions\2017SmartDashboardExtensions
    
    cmd /c gradlew.bat build
    
after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: cd ../..
- cmd: dir
- cmd: codecov -f "RobotCode/snobot2017/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "RobotCode/SnobotRobotLibs/build/reports/jacoco/test/jacocoTestReport.xml"

artifacts:
- path: SmartDashboardExtensions/2017SmartDashboardExtensions/build/libs
  name: SmartDashboardExtensions
 