thresholds:
  min: !!com.snobot.vision.HslThreshold
    hue: 27
    sat: 170
    lum: 110
  max: !!com.snobot.vision.HslThreshold
    hue: 92
    sat: 255
    lum: 255


filter: !!com.snobot.vision_app.app2017.java_algorithm.common.FilterParams
  minContoursSolidity: 0.0
  maxContoursSolidity: 100.0
  
  minHeight: 0.0
  maxHeight: 250
  
  minWidth: 5
  maxWidth: 100
  
  minRatio: 0.0
  maxRatio: 1000.0
  
  minVertices: 0.0
  maxVertices: 1000000.0
  
  minArea: 250.0
  minPerimeter: 0.0
  
  
  
  
  
 # minHeight: 0.0
 # maxHeight: 250
 # 
 # minWidth: 0
 # maxWidth: 1000.0
 # 
 # minRatio: 0.0
 # maxRatio: 1000.0
 # 
 # minVertices: 0.0
 # maxVertices: 1000000.0
 # 
 # minArea: 125.0
 # minPerimeter: 0.0
  
  