
one_at_a_time: true
threshold_config: peg_test_20170126/threshold_config.yml
images: 
    - ../../Vision/Images\test_images_20170126\2ft.jpg
    - ../../Vision/Images\test_images_20170126\3ft.jpg
    
    - ../../Vision/Images\test_images_20170126\1ft 45deg.jpg
    - ../../Vision/Images\test_images_20170126\1.5ft 45deg.jpg
    - ../../Vision/Images\test_images_20170126\2ft 45deg.jpg
    - ../../Vision/Images\test_images_20170126\3ft 45deg.jpg
