thresholds:
  min: !!com.snobot.vision.HslThreshold
    hue: 27
    lum: 44
    sat: 172
  max: !!com.snobot.vision.HslThreshold
    hue: 92
    lum: 255
    sat: 255

filter: !!com.snobot.vision_app.app2017.java_algorithm.common.FilterParams
  maxContoursSolidity: 100.0
  maxHeight: 250.0
  maxRatio: 1000.0
  maxVertices: 1000000.0
  maxWidth: 60.0
  minArea: 125.0
  minContoursSolidity: 0.0
  minHeight: 0.0
  minPerimeter: 0.0
  minRatio: 0.0
  minVertices: 0.0
  minWidth: 28.0