
one_at_a_time: true
threshold_config: peg_test_20170202/threshold_config.yml
images: 

    - ../../Vision/Images\test_images_20170202\0 X\1.0_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\1.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\2.0_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\2.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\3.0_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\3.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\4.0_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\4.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\5.0_5_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\5.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\6.0_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\6.5_0_0.jpg
    - ../../Vision/Images\test_images_20170202\0 X\7.0_0_0.jpg

    #- ../../Vision/Images\test_images_20170202\2 X\2.5_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\3.0_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\3.5_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\4.0_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\4.5_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\5.0_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\5.5_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\6.0_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\6.5_2_0.jpg
    #- ../../Vision/Images\test_images_20170202\2 X\7.0_2_0.jpg

    #- ../../Vision/Images\test_images_20170202\-2 X\3.0_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\3.5_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\4.0_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\4.5_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\5.0_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\5.5_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\6.0_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\6.5_-2_0.jpg
    #- ../../Vision/Images\test_images_20170202\-2 X\7.0_-2_0.jpg
